# Generated by Django 4.2.3 on 2023-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eloquent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Api key'),
        ),
        migrations.AlterField(
            model_name='device',
            name='remote_address',
            field=models.GenericIPAddressField(verbose_name='Ip Address'),
        ),
    ]
