# Generated by Django 4.2.3 on 2023-07-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eloquent_app', '0002_alter_device_api_key_alter_device_remote_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='field_1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_10',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_3',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_4',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_5',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_6',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_7',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_8',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_9',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_10',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_3',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_4',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_5',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_6',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_7',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_8',
        ),
        migrations.RemoveField(
            model_name='device',
            name='field_id_9',
        ),
    ]
